<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>Approval_Process_Approved_email_template</fullName>
        <description>Approval Process Approved email template</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>DefaultWorkflowUser</senderType>
        <template>One_Key_Email_Template/CAS_OneKey_Approval_Response</template>
    </alerts>
    <alerts>
        <fullName>Approval_Process_Rejected_email_template</fullName>
        <description>Approval Process Rejected email template</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>One_Key_Email_Template/CAS_OneKey_Approval_Response</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA_CSM_CREATE_AssignedCaseNotification</fullName>
        <description>CAS WEA CSM CREATE AssignedCaseNotification</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>CRM_MC_Workflow_Templates/CAS_ET_CSM_CREATE_AssignNotification</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_CS_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH CS E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_DE_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH DE E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_EL_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH EL E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_FR_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH FR E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_HU_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH HU E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_CS_Case_Closure</fullName>
        <description>CSM TECH CS Case Closure</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Czech_Templates/ET_TECH_CZ_Case_Closure</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_CS_Case_Comment</fullName>
        <description>CSM TECH CS Case Comment</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Czech_Templates/ET_TECH_CZ_Case_Comment</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_CS_Case_Creation</fullName>
        <description>CSM TECH CS Case Creation</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Czech_Templates/ET_TECH_CZ_Case_Creation</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_CS_Case_Creation_Portal</fullName>
        <description>CSM TECH CS Case Creation Portal</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Czech_Templates/ET_TECH_CZ_Case_Creation_Portal</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_CS_Case_Resolution</fullName>
        <description>CSM TECH CS Case Resolution</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Czech_Templates/ET_TECH_CZ_Case_Resolution</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_IT_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH IT E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_PL_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH PL E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_RO_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH RO E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_RU_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH RU E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_EL_Case_Closure</fullName>
        <description>CSM TECH EL Case Closure</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Greek_Templates/ET_TECH_GR_Case_Closure</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_UK_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH UK E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_EL_Case_Comment</fullName>
        <description>CSM TECH EL Case Comment</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Greek_Templates/ET_TECH_GR_Case_Comment</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_EL_Case_Creation</fullName>
        <description>CSM TECH EL Case Creation</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Greek_Templates/ET_TECH_GR_Case_Creation</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_EL_Case_Creation_Portal</fullName>
        <description>CSM TECH EL Case Creation Portal</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Greek_Templates/ET_TECH_GR_Case_Creation_Portal</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_EL_Case_Resolution</fullName>
        <description>CSM_TECH_EL_Case_Resolution</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Greek_Templates/ET_TECH_GR_Case_Resolution</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_nl_NL_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH nl_NL E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_pt_PT_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH pt_PT E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_ES_E2C_Case_Creation_replytocsm</fullName>
        <description>CSM TECH E2C Case Creation replytocsm</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Creation_ReplyToCSM</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_HU_Case_Closure</fullName>
        <description>CSM TECH HU Case Closure</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Hungarian_Templates/ET_TECH_HU_Case_Closure</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_HU_Case_Comment</fullName>
        <description>CSM TECH HU Case Comment</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Hungarian_Templates/ET_TECH_HU_Case_Comment</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_HU_Case_Creation</fullName>
        <description>CSM TECH HU Case Creation</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Hungarian_Templates/ET_TECH_HU_Case_Creation</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_HU_Case_Creation_Portal</fullName>
        <description>CSM TECH HU Case Creation Portal</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Hungarian_Templates/ET_TECH_HU_Case_Creation_Portal</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_HU_Case_Resolution</fullName>
        <description>CSM TECH HU Case Resolution</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Hungarian_Templates/ET_TECH_HU_Case_Resolution</template>
    </alerts>
    <alerts>
        <fullName>CSM_RnD_E2C_Case_Creation_BlankContact</fullName>
        <description>CSM RnD E2C Case Creation BlankContact</description>
        <protected>false</protected>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>R_D_Acknowledge_Email/Generic_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_CSM_Closed_Survey_Lupin</fullName>
        <description>CAS_CSM_Closed_Survey_Lupin</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>DefaultWorkflowUser</senderType>
        <template>CRM_MC_Workflow_Templates/CAS_ET_TECH_Case_Closed_Lupin</template>
    </alerts>
    <alerts>
        <fullName>CAS_CSS_CD_RnD_Case_Closure</fullName>
        <description>CAS CSS CD RnD Case Closure</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/CAS_CSS_CD_RnD_Case_Closed</template>
    </alerts>
    <alerts>
        <fullName>CAS_EA24_SendEmailNotificationBefore48HoursForSLADeadline</fullName>
        <description>CAS_EA24_SendEmailNotificationBefore48HoursForSLADeadline</description>
        <protected>false</protected>
        <recipients>
            <field>CaseOriginatorEmail__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Data_English_Templates/CAS_ET_CSM_DATA_MILESTONE_SLA_DEADLINE</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA02_CSM_ACN_Standard_Case_Auto_Response_Email</fullName>
        <description>CAS_WEA02_CSM_ACN_Standard Case Auto-Response Email</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>DefaultWorkflowUser</senderType>
        <template>unfiled$public/CAS_ET02_CSM_Standard_Case_Auto_Response_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA03_CSM_ACN_Canada_Case_Auto_Response_Email</fullName>
        <description>CAS_WEA03_CSM_ACN_Canada Case Auto-Response Email</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET03_CSM_Canada_Case_Auto_Response_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA04_CSM_ACN_Spanish_Case_Auto_Response_Email</fullName>
        <description>CAS_WEA04_CSM_ACN_Spanish Case Auto-Response Email</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET04_CSM_Spanish_Case_Auto_Response_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA05_CSM_ACN_French_Case_Auto_Response_Email</fullName>
        <description>CAS_WEA05_CSM_ACN_ French Case Auto-Response Email</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET05_CSM_French_Case_Auto_Response_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA06_CSM_ACN_Canada_Case_Resolution_Email_Template</fullName>
        <description>CAS_WEA06_CSM_ACN_Canada Case Resolution Email Template</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET06_CSM_Canada_Case_Resolution_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA07_CSM_ACN_Spanish_Case_Resolution_Email_Template</fullName>
        <description>CAS_WEA07_CSM_ACN_Spanish Case Resolution Email Template</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET07_CSM_Spanish_Case_Resolution_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CSM_Email_Alert</fullName>
        <description>CSM Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/Email_to_contact_for_case</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA08_CSM_ACN_Canada_Case_Resolution_Email_Template</fullName>
        <description>CAS_WEA08_CSM_ACN_French Case Resolution Email Template</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET08_CSM_French_Case_Resolution_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA10_CSM_ACN_CanadaResolutionEmailTemplate</fullName>
        <description>CAS_WEA10_CSM_ACN_SendCanadaResolutionEmailTemplate</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET06_CSM_Canada_Case_Resolution_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA10_CSM_ACN_CaseClosureEmailAlert</fullName>
        <description>CAS_WEA10_CSM_ACN_CanadaCaseClosureEmailAlert</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET10_CSM_CanadaCaseClosureEmailTemplate</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA11_CSM_ACN_SpanishCaseClosureEmailAlert</fullName>
        <description>CAS_WEA11_CSM_ACN_SpanishCaseClosureEmailAlert</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET11_CSM_SpanishCaseClosureEmailTemplate</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA12_CSM_ACN_FrenchCaseClosureEmailAlert</fullName>
        <description>CAS_WEA12_CSM_ACN_FrenchCaseClosureEmailAlert</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET12_CSM_FrenchCaseClosureEmailTemplate</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA13_CSM_ACN_English_Case_Auto_Response_Email</fullName>
        <description>CAS_WEA13_CSM_ACN_ English Case Auto-Response Email</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET13_CSM_English_Case_Auto_Response_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA14_CSM_ACN_English_Case_Resolution_Email_Template</fullName>
        <description>CAS_WEA14_CSM_ACN_English Case Resolution Email Template</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET14_CSM_English_Case_Resolution_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA15_CSM_ACN_EnglishCaseClosureEmailAlert</fullName>
        <description>CAS_WEA15_CSM_ACN_EnglishCaseClosureEmailAlert</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET15_CSM_EnglishCaseClosureEmailTemplate</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA16_CSM_ACN_StoppedSince</fullName>
        <ccEmails>karishmastar9@gmail.com</ccEmails>
        <description>CAS_WEA16_CSM_ACN_StoppedSince</description>
        <protected>false</protected>
        <recipients>
            <type>creator</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET16_CSM_StoppedSince</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA17_CSM_ACN_ResolutionTimeElapsed</fullName>
        <description>CAS_WEA17_CSM_ACN_ResolutionTimeElapsed</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET17_CSM_ResolutionTimeElapsed</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA18_CSM_ACN_NewCase</fullName>
        <description>CAS_WEA18_CSM_ACN_NewCase</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/CAS_ET02_CSM_Standard_Case_Auto_Response_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA22_AddNewCommentContact</fullName>
        <description>CAS_WEA22_AddNewCommentContact</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>email2casecsm@quintilesims.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/CAS_ET19_CSM_NewCaseComment</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA23_AddNewCommentOwner</fullName>
        <description>CAS_WEA23_AddNewCommentOwner</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>email2casecsm@quintilesims.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/CAS_ET19_CSM_NewCaseComment</template>
    </alerts>
    <alerts>
        <fullName>CAS_WEA02_CSM_ACN_CaseEscalation</fullName>
        <description>CAS_WEA02_CSM_ACN_CaseEscalation</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/CAS_ET01_CSM_CaseEscalationNotification</template>
    </alerts>
    <alerts>
        <fullName>CSM_ET_TECH_EN_Case_Status_Change_By_Batch_Job</fullName>
        <description>CSM_ET_TECH_EN_Case_Status_Change_By_Batch_Job</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Status_Change_By_Batch_Job</template>
    </alerts>
    <alerts>
        <fullName>CSM_ET_TECH_EN_Case_Status_Change_By_Batch_Job_Queue</fullName>
        <description>CSM_ET_TECH_EN_Case_Status_Change_By_Batch_Job_Queue</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Status_Change_By_Batch_Job_Queue</template>
    </alerts>
	<alerts>
        <fullName>CSM_TECH_UK_Case_Closure</fullName>
        <description>CSM TECH UK Case Closure</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Ukraine_Templates/TECH_UK_Case_Closure</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_UK_Case_Creation</fullName>
        <description>CSM TECH UK Case Creation</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>replytocsm@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Ukraine_Templates/TECH_UK_Case_Creation</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_UK_Case_Creation_Portal</fullName>
        <description>CSM TECH UK Case Creation Portal</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Ukraine_Templates/ET_TECH_UK_Case_Creation_Portal</template>
    </alerts>
    <alerts>
        <fullName>CSM_TECH_UK_Case_Resolution</fullName>
        <description>CSM TECH UK Case Resolution</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>replytocsm@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Tech_Ukraine_Templates/TECH_UK_Case_Resolution</template>
    </alerts>
    <alerts>
        <fullName>notify_Contact</fullName>
        <description>notify Contact</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>unfiled$public/Email_to_contact_for_case</template>
    </alerts>
    <alerts>
        <fullName>Case_Pending_Resolution_for_2_Days</fullName>
        <description>Case Pending Resolution for 2 Days</description>
        <protected>false</protected>
        <recipients>
            <field>ContactId</field>
            <type>contactLookup</type>
        </recipients>
        <senderAddress>no.reply.support@iqvia.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>English_Templates/ET_TECH_EN_Case_Pending_Resolution_for_2_Days</template>
    </alerts>
    <fieldUpdates>
        <fullName>CAS_WFU01_CSM_SetInProgress</fullName>
        <description>CSM-ACN-S-0007 - Update status to In progress</description>
        <field>Status</field>
        <literalValue>In Progress</literalValue>
        <name>CAS_WFU01_CSM_SetInProgress</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU01_CSM_UpdateStatus</fullName>
        <description>CSM-ACN-S-0007  - Update status to in progress and substatus to null if scheduled date is met</description>
        <field>Status</field>
        <literalValue>In Progress</literalValue>
        <name>CAS_WFU01_CSM_UpdateStatus</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU01_CSM_UpdateStatusInProgress</fullName>
        <description>CSM-ACN-S-0007 - Update Status to In Progress</description>
        <field>Status</field>
        <literalValue>In Progress</literalValue>
        <name>CAS_WFU01_CSM_UpdateStatusInProgress</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU01_CSM_UpdateStatusToInProgress</fullName>
        <description>CSM-ACN-S-0007 - Update status to &apos;In progress</description>
        <field>Status</field>
        <literalValue>In Progress</literalValue>
        <name>CAS_WFU01_CSM_UpdateStatusToInProgress</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU01_CSM_UpdateSubStatus</fullName>
        <description>CSM-ACN-S-0007 - Set SubStatus to blank</description>
        <field>SubStatus__c</field>
        <name>CAS_WFU01_CSM_UpdateSubStatus</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU02_CSM_SetFieldBlank</fullName>
        <description>CSM-ACN-S-0007 - Set substatus to blank</description>
        <field>SubStatus__c</field>
        <name>CAS_WFU02_CSM_SetFieldBlank</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU02_CSM_UpdateStatus</fullName>
        <description>CSM-ACN-S-0007 - Update status to &apos;In Progress</description>
        <field>Status</field>
        <literalValue>In Progress</literalValue>
        <name>CAS WFU02 CSM UpdateStatus</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU02_CSM_UpdateSubStatusToBlank</fullName>
        <description>CSM-ACN-S-0007 - Update substatus to blank</description>
        <field>SubStatus__c</field>
        <name>CAS_WFU02_CSM_UpdateSubStatusToBlank</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU02_CSM_UpdateSubstatus</fullName>
        <description>CSM-ACN-S-0007 - Update substatus to NULL id scheduled date has been met</description>
        <field>SubStatus__c</field>
        <name>CAS WFU02 CSM UpdateSubstatus</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU07_CSM_CheckIsThisASpecialHan</fullName>
        <description>CSM - ACN - S0062</description>
        <field>IsThisASpecialHandlingClient__c</field>
        <literalValue>1</literalValue>
        <name>CAS_WFU07_CSM_CheckIsThisASpecialHan</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Self_Registration_Date</fullName>
        <field>Self_Registration_Date__c</field>
        <formula>Today()+$Setup.CSM_User_Self_Registration__c.Add_days_to_Self_Registration__c</formula>
        <name>Update Self Registration Date</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Self_Registration_Date1</fullName>
        <field>Self_Registration_Date__c</field>
        <formula>Today()+$Setup.CSM_User_Self_Registration__c.Add_days_to_Self_Registration__c</formula>
        <name>Update Self Registration Date1</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU19_CSM_NewMilestoneOngoing</fullName>
        <description>CSM - ACN - S-0014 - Next Milestone Status Ongoing</description>
        <field>NextMilestoneStatus__c</field>
        <literalValue>Ongoing</literalValue>
        <name>CAS_WFU19_CSM_NewMilestoneOngoing</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU20_CSM_NewMilestone2Hours</fullName>
        <description>CSM - ACN - S-0014 -  Next Milestone status Remaining 2 hours</description>
        <field>NextMilestoneStatus__c</field>
        <literalValue>Remaining 2 hours</literalValue>
        <name>CAS_WFU20_CSM_NewMilestone2Hours</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU21_CSM_NewMilestone8Hours</fullName>
        <description>CSM - ACN - S-0014 - Next milestone status Remaining 8 hours</description>
        <field>NextMilestoneStatus__c</field>
        <literalValue>Remaining 8 hours</literalValue>
        <name>CAS_WFU21_CSM_NewMilestone8Hours</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU22_CSM_NewMilestone16Hours</fullName>
        <description>CSM - ACN - S-0014 - Next Milestone status 16 hours</description>
        <field>NextMilestoneStatus__c</field>
        <literalValue>Remaining 16 hours</literalValue>
        <name>CAS_WFU22_CSM_NewMilestone16Hours</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU23_CSM_NewMilestoneReached</fullName>
        <description>CSM - ACN- S-0014 - Next Milestone status Reached</description>
        <field>NextMilestoneStatus__c</field>
        <literalValue>Reached</literalValue>
        <name>CAS_WFU23_CSM_NewMilestoneReached</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU24_CSM_NewMilestoneCompleted</fullName>
        <description>CSM - ACN - S-0014 - Next milestone status Completes</description>
        <field>NextMilestoneStatus__c</field>
        <literalValue>Completed</literalValue>
        <name>CAS_WFU24_CSM_NewMilestoneCompleted</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU35_Update_Survey_Sent_Date</fullName>
        <description>CSM - Qualtric Integration</description>
        <field>Update_Survey_Sent_Date__c</field>
        <literalValue>1</literalValue>
        <name>CAS_WFU35_Update_Survey_Sent_Date</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU40_CSM_NewMilestone2DaysRemaining</fullName>
        <field>NextMilestoneStatus__c</field>
        <literalValue>2 days remaining</literalValue>
        <name>CAS_WFU40_CSM_NewMilestone2DaysRemaining</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU41_CSM_NewMilestone1DayRemaining</fullName>
        <field>NextMilestoneStatus__c</field>
        <literalValue>1 day remaining</literalValue>
        <name>CAS_WFU41_CSM_NewMilestone1DayRemaining</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU42_CSM_NewMilestoneBreached</fullName>
        <field>NextMilestoneStatus__c</field>
        <literalValue>Breached</literalValue>
        <name>CAS_WFU42_CSM_NewMilestoneBreached</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU43_CSM_UpdateCSATSentInCase</fullName>
        <field>CSAT_Sent__c</field>
        <formula>1</formula>
        <name>CAS_WFU43_CSM_UpdateCSATSentInCase</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU_CSM_InitialResponseTimeFailed</fullName>
        <description>CSM-2195: Initial Response time Failed update on Case Originator Name</description>
        <field>CaseOriginatorName__c</field>
        <formula>&quot;Initial Response Time Failed&quot;</formula>
        <name>CAS_WFU_CSM_InitialResponseTimeFailed</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU_CSM_MilestoneViolationUpdate</fullName>
        <field>Milestone_Violation__c</field>
        <literalValue>1</literalValue>
        <name>CAS_WFU_CSM_MilestoneViolationUpdate</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>CAS_WFU_CSM_ResolutionPlanFailed</fullName>
        <field>CaseOriginatorName__c</field>
        <formula>&quot;Resolution Plan Failed&quot;</formula>
        <name>CAS_WFU_CSM_ResolutionPlanFailed</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Next_Status_Milestone_Update</fullName>
        <field>NextMilestoneStatus__c</field>
        <literalValue>Remaining 2 hours</literalValue>
        <name>Next Status Milestone Update</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_Survey_Sent_Date</fullName>
        <field>Update_Survey_Sent_Date__c</field>
        <literalValue>1</literalValue>
        <name>Update Survey Sent Date</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_status_to_Rejected_for_on_key</fullName>
        <description>Update status to Rejected for on key</description>
        <field>Status</field>
        <literalValue>Rejected</literalValue>
        <name>Update status to Rejected for on key</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update_status_to_approved_for_on_key</fullName>
        <description>Update status to approved for on key</description>
        <field>Status</field>
        <literalValue>Approved</literalValue>
        <name>Update status to approved for on key</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <outboundMessages>
        <fullName>CAS_OB02_CSM_QualtricsEmailOutboud_RnD</fullName>
        <apiVersion>52.0</apiVersion>
        <endpointUrl>https://iad1.qualtrics.com/triggers/api/v1/event?eventType=SalesforceOutboundMessage&amp;s=SV_a5Xzj9hhJkqgFyS&amp;u=UR_4NkZvLn7k6XtM9f&amp;t=OC_TQFG5w9BEMm8ZM5&amp;b=imshealth</endpointUrl>
        <fields>AccountId</fields>
        <fields>CaseNumber</fields>
        <fields>ContactId</fields>
        <fields>CreatedDate</fields>
        <fields>Description</fields>
        <fields>Id</fields>
        <fields>Resolution__c</fields>
        <fields>Subject</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>m.thomas@fr.imshealth.com.qi</integrationUser>
        <name>CAS_OB02_CSM_QualtricsEmailOutboud_RnD</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <outboundMessages>
        <fullName>CAS_OB03_CSM_QualtricsEmailOutboud_TechO</fullName>
        <apiVersion>52.0</apiVersion>
        <endpointUrl>https://iad1.qualtrics.com/triggers/api/v1/event?eventType=SalesforceOutboundMessage&amp;s=SV_2aSgS7c1OG0w9wx&amp;u=UR_4NkZvLn7k6XtM9f&amp;t=OC_3enpRf0Sk5xDho0&amp;b=imshealth</endpointUrl>
        <fields>AccountId</fields>
        <fields>CaseNumber</fields>
        <fields>ContactId</fields>
        <fields>CreatedDate</fields>
        <fields>CreatedDate__c</fields>
        <fields>Description</fields>
        <fields>Id</fields>
        <fields>ProductName__c</fields>
        <fields>Resolution__c</fields>
        <fields>SLA_Policies__c</fields>
        <fields>Subject</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>ci_deployment@iqvia.com</integrationUser>
        <name>CAS_OB03_CSM_QualtricsEmailOutboud_TechO</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <outboundMessages>
        <fullName>CAS_OB04_CSM_QualtricsEmailOutboud_TechO</fullName>
        <apiVersion>52.0</apiVersion>
        <endpointUrl>https://iad1.qualtrics.com/triggers/api/v1/event?eventType=SalesforceOutboundMessage&amp;s=SV_8ppVTpIdZAPxGMR&amp;u=UR_4NkZvLn7k6XtM9f&amp;t=OC_2qEHsfFZ60pLBer&amp;b=imshealth</endpointUrl>
        <fields>AccountId</fields>
        <fields>CaseNumber</fields>
        <fields>ContactId</fields>
        <fields>CreatedDate</fields>
        <fields>CreatedDate__c</fields>
        <fields>Description</fields>
        <fields>Id</fields>
        <fields>ProductName__c</fields>
        <fields>Resolution__c</fields>
        <fields>SLA_Policies__c</fields>
        <fields>Subject</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>ci_deployment@iqvia.com</integrationUser>
        <name>CAS_OB04_CSM_QualtricsEmailOutboud_TechO</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <outboundMessages>
        <fullName>CAS_OB05_CSM_QualtricsEmailOutboud_DATA</fullName>
        <apiVersion>52.0</apiVersion>
        <endpointUrl>https://iad1.qualtrics.com/triggers/api/v1/event?eventType=SalesforceOutboundMessage&amp;s=SV_1TbdHu9R45OGoAJ&amp;u=UR_4NkZvLn7k6XtM9f&amp;t=OC_3FJQsrOfM6lGV3M&amp;b=imshealth</endpointUrl>
        <fields>AccountCountry__c</fields>
        <fields>AccountId</fields>
        <fields>CaseNumber</fields>
        <fields>ContactId</fields>
        <fields>CreatedDate</fields>
        <fields>CreatedDate__c</fields>
        <fields>Description</fields>
        <fields>Id</fields>
        <fields>ProductName__c</fields>
        <fields>Resolution__c</fields>
        <fields>SLA_Policies__c</fields>
        <fields>Subject</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>ci_deployment@iqvia.com</integrationUser>
        <name>CAS_OB05_CSM_QualtricsEmailOutboud_DATAB</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <outboundMessages>
        <fullName>CAS_OB07_CSM_QualtricsEmailOutboud_RnD_S</fullName>
        <apiVersion>63.0</apiVersion>
        <description>As per CSM-3186</description>
        <endpointUrl>https://iad1.qualtrics.com/triggers/api/v1/event?eventType=SalesforceOutboundMessage&amp;s=SV_6gocrwZCEtEaezQ&amp;u=UR_4NkZvLn7k6XtM9f&amp;t=OC_msvO1jngAooySl3&amp;b=imshealth</endpointUrl>
        <fields>CaseNumber</fields>
        <fields>ContactId</fields>
        <fields>CreatedDate</fields>
        <fields>Description</fields>
        <fields>Id</fields>
        <fields>Subject</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>m.thomas@fr.imshealth.com.qi</integrationUser>
        <name>CAS_OB07_CSM_QualtricsEmailOutboud_RnD_S</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <outboundMessages>
        <fullName>CAS_WOM01_CSM_QualtricsEmailOutboud</fullName>
        <apiVersion>52.0</apiVersion>
        <endpointUrl>https://iad1.qualtrics.com/triggers/api/v1/event?eventType=SalesforceOutboundMessage&amp;s=SV_5swmL9b0BRF7wd7&amp;u=UR_4NkZvLn7k6XtM9f&amp;t=OC_sXuYsi33UjPZjfH&amp;b=imshealth</endpointUrl>
        <fields>AccountId</fields>
        <fields>CaseNumber</fields>
        <fields>ContactId</fields>
        <fields>Contact_Partner_Type__c</fields>
        <fields>CreatedDate</fields>
        <fields>CreatedDate__c</fields>
        <fields>Description</fields>
        <fields>Id</fields>
        <fields>ProductName__c</fields>
        <fields>Resolution__c</fields>
        <fields>SLA_Policies__c</fields>
        <fields>Subject</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>ci_deployment@iqvia.com</integrationUser>
        <name>CAS_WOM01_CSM_QualtricsEmailOutboud</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <outboundMessages>
        <fullName>CAS_OB05_CSM_QualtricsEmailOutboud_TechO</fullName>
        <apiVersion>57.0</apiVersion>
        <endpointUrl>https://iad1.qualtrics.com/triggers/api/v1/event?eventType=SalesforceOutboundMessage&amp;s=SV_7WDUr2lu1MGr3pk&amp;u=UR_4NkZvLn7k6XtM9f&amp;t=OC_lsMp3rslWnVe0iz&amp;b=imshealth</endpointUrl>
        <fields>AccountId</fields>
        <fields>CaseNumber</fields>
        <fields>ContactId</fields>
        <fields>CreatedDate</fields>
        <fields>CreatedDate__c</fields>
        <fields>Description</fields>
        <fields>Id</fields>
        <fields>ProductName__c</fields>
        <fields>Resolution__c</fields>
        <fields>SLA_Policies__c</fields>
        <fields>Subject</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>ci_deployment@iqvia.com</integrationUser>
        <name>CAS_OB05_CSM_QualtricsEmailOutboud_TechO</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
	<rules>
        <fullName>CAS_WR31_CSM_SetStatusFieldBasedOnScheduledDate</fullName>
        <active>false</active>
        <criteriaItems>
            <field>Case.ScheduledDatetime__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Status</field>
            <operation>notEqual</operation>
            <value>Closed,Resolved with Customer</value>
        </criteriaItems>
        <description>CSM-ACN-S-0183 - WR that sets Status to &apos;In progress&apos; &amp; substatus to blank if scheduled date is reached.</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>CAS_WFU01_CSM_SetInProgress</name>
                <type>FieldUpdate</type>
            </actions>
            <actions>
                <name>CAS_WFU02_CSM_SetFieldBlank</name>
                <type>FieldUpdate</type>
            </actions>
            <offsetFromField>Case.ScheduledDatetime__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Hours</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>CAS_WR58_CSM_CSATTechnoOptionB</fullName>
        <actions>
            <name>CAS_WFU35_Update_Survey_Sent_Date</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_WFU43_CSM_UpdateCSATSentInCase</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_WOM01_CSM_QualtricsEmailOutboud</name>
            <type>OutboundMessage</type>
        </actions>
        <active>false</active>
        <description>CSM S-0211 CSAT Step 2 - Qualtrics Interface_techno</description>
        <formula>AND (OR(ISPICKVAL(Status,&apos;Resolved with Customer&apos;),
	AND(ISPICKVAL(Status,&apos;Awaiting&apos;),ISPICKVAL(SubStatus__c,&apos;Customer Confirmation to Close&apos;))),RecordType.DeveloperName = &apos;TechnologyCase&apos;,INCLUDES(Account.C_SAT_Survey_Option__c, &apos;TS Option B&apos;),ISBLANK(TEXT( SLA_Policies__c )),
 OR (CONTAINS(InitialQueue__c, &quot;T1&quot;),
NOT(ISBLANK(Contact_Partner_Type__c))),NOT(ISBLANK(Contact.Email)), Contact.Survey_Opt_Out__c = false, OR(TODAY() - IF(ISBLANK(Account.CSAT_Frequency_For_TechSol__c), $Setup.C_SAT_Default_Frequency__c.Default_Frequency_For_Techno__c, Account.CSAT_Frequency_For_TechSol__c) &gt;= Contact.C_SAT_Last_Submitted_Date__c, ISBLANK(Contact.C_SAT_Last_Submitted_Date__c), Force_CSAT_Email_Survey__c = true), ReOpened__c = false)</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>CAS_WR59_CSM_CSATRnDOptionB</fullName>
        <actions>
            <name>CAS_WFU35_Update_Survey_Sent_Date</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_WFU43_CSM_UpdateCSATSentInCase</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_OB02_CSM_QualtricsEmailOutboud_RnD</name>
            <type>OutboundMessage</type>
        </actions>
        <active>false</active>
        <description>CSM S-0311 CSAT Step 2 - Qualtrics Interface_R&amp;D</description>
        <formula>OR( AND(  ISPICKVAL( Status , &apos;Closed&apos;) , RecordType.DeveloperName = &apos;RandDCase&apos;, INCLUDES(Account.C_SAT_Survey_Option__c, &apos;R&amp;D Option B&apos;), NOT(ISBLANK(Contact.Email)), NOT(ISPICKVAL(LOS__c,&quot;Registry Support&quot;)),NOT(ISPICKVAL(LOS__c,&quot;Alexion&quot;)), NOT(ISPICKVAL(LOS__c,&quot;Emergency&quot;)), NOT(ISPICKVAL(LOS__c,&quot;Bluebirdbio&quot;)), NOT(CONTAINS(SubType2__c,&quot;Administration&quot;)), NOT(CONTAINS(SubType2__c,&quot;Novella&quot;)), Contact.Email &lt;&gt; &quot;infosarioprod@service-now.com&quot;, NOT(ISPICKVAL(SubStatus__c ,&quot;Non-Actionable&quot;)), OR(TODAY() - IF(ISBLANK(Account.CSAT_Frequency_For_R_D__c),$Setup.C_SAT_Default_Frequency__c.Default_Frequency_For_R_D__c,Account.CSAT_Frequency_For_R_D__c) &gt;= Contact.C_SAT_Last_Submitted_Date__c, ISBLANK(Contact.C_SAT_Last_Submitted_Date__c) ), Contact.Survey_Opt_Out__c = false,ReOpened__c = false ), AND( ISPICKVAL( Status , &apos;Closed&apos;), RecordType.DeveloperName = &apos;RandDCase&apos;, INCLUDES(Account.C_SAT_Survey_Option__c, &apos;R&amp;D Option B&apos;), ISPICKVAL(LOS__c,&quot;Registry Support&quot;), SubType1__c =&quot;ACS_NSQIP_Bariatric&quot;, SubType2__c &lt;&gt;&quot;Administration&quot;, Contact.Email &lt;&gt; &quot;infosarioprod@service-now.com&quot;, NOT(ISPICKVAL(SubStatus__c ,&quot;Non-Actionable&quot;)), OR(TODAY() - IF(ISBLANK(Account.CSAT_Frequency_For_R_D__c),$Setup.C_SAT_Default_Frequency__c.Default_Frequency_For_R_D__c,Account.CSAT_Frequency_For_R_D__c) &gt;= Contact.C_SAT_Last_Submitted_Date__c, ISBLANK(Contact.C_SAT_Last_Submitted_Date__c) ), Contact.Survey_Opt_Out__c = false, ReOpened__c = false ), AND( ISPICKVAL( Status , &apos;Closed&apos;), RecordType.DeveloperName = &apos;RandDCase&apos;, INCLUDES(Account.C_SAT_Survey_Option__c, &apos;R&amp;D Option B&apos;), ISPICKVAL(LOS__c,&quot;Registry Support&quot;), NOT(CONTAINS(SubType1__c,&quot;ACS&quot;)), SubType2__c &lt;&gt;&quot;Administration&quot;, Contact.Email &lt;&gt; &quot;infosarioprod@service-now.com&quot;, NOT(ISPICKVAL(SubStatus__c ,&quot;Non-Actionable&quot;)), OR(TODAY() - IF(ISBLANK(Account.CSAT_Frequency_For_R_D__c),$Setup.C_SAT_Default_Frequency__c.Default_Frequency_For_R_D__c,Account.CSAT_Frequency_For_R_D__c) &gt;= Contact.C_SAT_Last_Submitted_Date__c, ISBLANK(Contact.C_SAT_Last_Submitted_Date__c) ), Contact.Survey_Opt_Out__c = false , ReOpened__c = false) )</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>CAS_WR60_CSM_CSATTechnoOptionD</fullName>
        <actions>
            <name>CAS_WFU35_Update_Survey_Sent_Date</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_WFU43_CSM_UpdateCSATSentInCase</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_OB03_CSM_QualtricsEmailOutboud_TechO</name>
            <type>OutboundMessage</type>
        </actions>
        <active>false</active>
        <formula>AND (OR (ISPICKVAL(Status,&apos;Resolved with Customer&apos;),
	AND(ISPICKVAL(Status,&apos;Awaiting&apos;),ISPICKVAL(SubStatus__c,&apos;Customer Confirmation to close&apos;))),RecordType.DeveloperName = &apos;TechnologyCase&apos;,INCLUDES(Account.C_SAT_Survey_Option__c, &apos;TS Option D&apos;),ISBLANK(TEXT( SLA_Policies__c )),CONTAINS(InitialQueue__c, &quot;T1&quot;),NOT(ISBLANK(Contact.Email)), Contact.Survey_Opt_Out__c = false, OR(TODAY() - IF(ISBLANK(Account.CSAT_Frequency_For_TechSol__c), $Setup.C_SAT_Default_Frequency__c.Default_Frequency_For_Techno__c,Account.CSAT_Frequency_For_TechSol__c) &gt;= Contact.C_SAT_Last_Submitted_Date__c,ISBLANK(Contact.C_SAT_Last_Submitted_Date__c), Force_CSAT_Email_Survey__c = true), ReOpened__c = false)</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>CAS_WR61_CSM_CSATTechnoCC_OptionD</fullName>
        <actions>
            <name>CAS_WFU35_Update_Survey_Sent_Date</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_WFU43_CSM_UpdateCSATSentInCase</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_OB03_CSM_QualtricsEmailOutboud_TechO</name>
            <type>OutboundMessage</type>
        </actions>
        <active>false</active>
        <description>CSAT Step 2 - Qualtrics Interface_techno</description>
        <formula>AND( 
ISPICKVAL( Status , &apos;Closed&apos;),
RecordType.DeveloperName =&apos;TechnologyCase&apos;,
NOT(ISBLANK(AccountId)),
NOT(ISBLANK(Contact.Email)),
NOT(ISBLANK(TEXT( SLA_Policies__c ))),
Contact.Survey_Opt_Out__c = false,
INCLUDES(Account.C_SAT_Survey_Option__c, &apos;TS Option D&apos;),
OR(Force_CSAT_Email_Survey__c = true, CONTAINS( InitialQueue__c, &quot;T1&quot;), CONTAINS(InitialQueue__c, &quot;T2&quot;)), ReOpened__c = false)</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>CAS_WR63_CSM_CSATTechnoOptionE</fullName>
        <actions>
            <name>CAS_OB04_CSM_QualtricsEmailOutboud_TechO</name>
            <type>OutboundMessage</type>
        </actions>
        <active>false</active>
        <formula>AND( ISPICKVAL( Status , &apos;Closed&apos;), RecordType.DeveloperName = &apos;TechnologyCase&apos;,INCLUDES(Account.C_SAT_Survey_Option__c, &apos;TS Option E&apos;),     ISBLANK(TEXT( SLA_Policies__c )), AND(CONTAINS(InitialQueue__c, &quot;T2&quot;),CONTAINS(CurrentQueue__r.Name, &quot;T2&quot;)), NOT(ISBLANK(Contact.Email)), Contact.Survey_Opt_Out__c = false, OR(TODAY() - IF(ISBLANK(Account.CSAT_Frequency_For_TechSol__c), $Setup.C_SAT_Default_Frequency__c.Default_Frequency_For_Techno__c, Account.CSAT_Frequency_For_TechSol__c) &gt;= Contact.C_SAT_Last_Submitted_Date__c, ISBLANK(Contact.C_SAT_Last_Submitted_Date__c), Force_CSAT_Email_Survey__c = true), ReOpened__c = false)</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>CAS_WR71_CSM_CSATDATAOptionB</fullName>
        <actions>
            <name>CAS_WFU35_Update_Survey_Sent_Date</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_WFU43_CSM_UpdateCSATSentInCase</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>CAS_OB05_CSM_QualtricsEmailOutboud_DATA</name>
            <type>OutboundMessage</type>
        </actions>
        <active>false</active>
        <formula>AND (ISPICKVAL( Status , &apos;Closed&apos;), RecordTypeName__c = &apos;DATACase&apos;, INCLUDES(Account.C_SAT_Survey_Option__c , &apos;DATA Option B&apos;), NOT(ISBLANK(Contact.Email)), Contact.Survey_Opt_Out__c = false, OR(TODAY() - IF(ISBLANK(Account.CSAT_Frequency_For_DATA__c), $Setup.C_SAT_Default_Frequency__c.Default_Frequency_For_DATA__c, Account.CSAT_Frequency_For_DATA__c) &gt;= Contact.C_SAT_Last_Submitted_Date__c, ISBLANK(Contact.C_SAT_Last_Submitted_Date__c), Force_CSAT_Email_Survey__c = true),   OR (NOT(ISPICKVAL(Account.AccountCountry__c,&apos;US&apos;)), AND(ISPICKVAL(Account.AccountCountry__c,&apos;US&apos;), NOT(ISPICKVAL(ResolutionCode__c,&apos;Client – Data Query Not Valid&apos;)), NOT(ISPICKVAL(ResolutionCode__c,&apos;Duplicate Inquiry&apos;)), NOT(ISPICKVAL(ResolutionCode__c,&apos;No longer required&apos;)), NOT(ISPICKVAL(ResolutionCode__c,&apos;No response from client&apos;)), NOT(ISPICKVAL(ResolutionCode__c,&apos;Other – Duplicate Request&apos;)), OR( SubType3__c = &apos;DDD OUTLET VOLUME INVESTIGATION&apos;,  SubType3__c = &apos;XPO PRESCRIBER VOLUME INVESTIGATION&apos;,  SubType3__c = &apos;ZIP/TERRITORY VOLUME/ TREND INVESTIGATION&apos;, SubType3__c = &apos;XPO PLAN VOLUME INVESTIGATION&apos;) ),AND(ISPICKVAL(Account.AccountCountry__c,&apos;US&apos;),NOT(ISPICKVAL(ResolutionCode__c,&apos;Client – Data Query Not Valid&apos;)), NOT(ISPICKVAL(ResolutionCode__c,&apos;Duplicate Inquiry&apos;)), NOT(ISPICKVAL(ResolutionCode__c,&apos;No longer required&apos;)), NOT(ISPICKVAL(ResolutionCode__c,&apos;No response from client&apos;)), NOT(ISPICKVAL(ResolutionCode__c,&apos;Other – Duplicate Request&apos;)), OR(ProductName__c =&apos;NPA&apos;,ProductName__c =&apos;NPA MARKET DYNAMICS&apos;,ProductName__c =&apos;NPA MONTHLY&apos;,ProductName__c =&apos;NPA WEEKLY&apos;,ProductName__c =&apos;NPA NEW TO BRAND&apos;,ProductName__c =&apos;NSP&apos;,ProductName__c =&apos;NSP – MONTHLY&apos;,ProductName__c =&apos;WEEKLY SALES PERSPECTIVES&apos;,ProductName__c =&apos;MULTI AUDIT&apos;),OR(SubType3__c =&apos;NATIONAL LOW COMPLEXITY&apos;,SubType3__c =&apos;NATIONAL MEDIUM COMPLEXITY&apos;,SubType3__c =&apos;NATIONAL HIGH COMPLEXITY&apos;) ) ) )</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>CAS_WR_CSM_Pending_Resolved_Case_Notification</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 ) AND (4 OR ( 5 AND 6)) AND 7</booleanFilter>
        <criteriaItems>
            <field>Case.Status</field>
            <operation>equals</operation>
            <value>Resolved with Customer</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>TechnologyCase</value>
        </criteriaItems>
        <criteriaItems>
            <field>Account.Name</field>
            <operation>notContain</operation>
            <value>Novo Nordisk</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.SendAutomaticAcknowledgmentEmail__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.SendAutomaticAcknowledgmentEmail__c</field>
            <operation>equals</operation>
            <value>Account Choice</value>
        </criteriaItems>
        <criteriaItems>
            <field>Account.SendAutomaticCaseAcknowledgmentEmail__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Low_Email_Notification_frequency__c</field>
            <operation>equals</operation>
            <value>False</value>
        </criteriaItems>
        <description>email will send to customer if resolved with customer exists for 48 Hours</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>Case_Pending_Resolution_for_2_Days</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>Case.StatusChangedTime__c</offsetFromField>
            <timeLength>48</timeLength>
            <workflowTimeTriggerUnit>Hours</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>CSM Self Registration Notification</fullName>
        <actions>
            <name>CSM_Email_Alert</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>Update_Self_Registration_Date1</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <booleanFilter>((1 AND 6) OR (7 AND 5)) AND 2 AND 3 AND 4 AND 8</booleanFilter>
        <criteriaItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>DATA Case</value>
        </criteriaItems>
        <criteriaItems>
            <field>Contact.Opt_Out_From__c</field>
            <operation>notEqual</operation>
            <value>Self Registration</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.Contact_Already_In_Self_Registration__c</field>
            <operation>equals</operation>
            <value>False</value>
        </criteriaItems>
        <criteriaItems>
            <field>Contact.Contact_User_Type__c</field>
            <operation>equals</operation>
            <value>HO User</value>
        </criteriaItems>
        <criteriaItems>
            <field>Account.CSH_Self_Registration__c</field>
            <operation>includes</operation>
            <value>Technology Solutions</value>
        </criteriaItems>
        <criteriaItems>
            <field>Account.CSH_Self_Registration__c</field>
            <operation>includes</operation>
            <value>Information Offering</value>
        </criteriaItems>
        <criteriaItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>TechnologyCase</value>
        </criteriaItems>
        <criteriaItems>
            <field>Contact.CSH_User__c</field>
            <operation>equals</operation>
            <value>No</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>notify_Contact</name>
                <type>Alert</type>
            </actions>
            <actions>
                <name>Update_Self_Registration_Date</name>
                <type>FieldUpdate</type>
            </actions>
            <offsetFromField>Case.Self_Registration_Date__c</offsetFromField>
            <timeLength>0</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
</Workflow>
