/**
 * This class used for constants used in CBEx project.
 * version : 1.0
 */
public class CON_CBEx {
    // This is all ProfileName Constant
    public static final String RDS_User = 'RDS User';
    public static final String administrator = 'Administrator';
    public static final String administratorSupport = 'IQVIA Salesforce Platform Support';
    public static final String Marketing_User_IQVIA = 'Marketing User IQVIA';
	public static final String ACCOUNT_OBJECT = 'Account';
    public static final String OPPORTUNITY_OBJECT = 'Opportunity';
    public static final String BIDHISTORY_OBJECT = 'Bid_History__c';
    public static final String RESOURCE_REQUEST_OBJECT = 'pse__Resource_Request__c';
    public static final String MULESOFT_SYNC_STATUS_PENDING = 'Pending';
}