/**
 * This class used for constants used in PEP project.
 * version : 1.0
 */
public class CON_PEP {
    public static final String S_P_PEP_COMMUNITY = 'PRM Community User';
    public static final String S_P_CSM_COMMUNITY = 'CSM Customer Community Plus Login User';    
    public static final String S_PARTNER_PORTAL = 'Partner Portal';
    public static final String S_PEP_MANAGER = 'Manager';
    public static final String S_PEP_CONSULTANT = 'Consultant';
    public static final String S_PEP_QUEUE = 'Queue';
    public static final String ALLIANCE_MANAGER= 'Alliance Manager';
    public static final String S_PEP_MANUAL_SHARE= 'Manual';
    public static final String S_PEP_ACCESS_EDIT= 'Edit';
    public static final String S_PEP_ACCESS_READ= 'Read';
    public static final String S_PEP_ORG_WIDE_ADD_NO_REPLY = 'no.reply.techpartners@iqvia.com';
    public static final String S_PEP_LD_STATUS_REGISTERED = 'Registered';
    public static final String S_PEP_LD_STATUS_CONVERTED = 'Converted';
    public static final String S_PEP_LD_STATUS_REJECTED = 'Closed - No Opportunity';
    public static final String S_PEP_LD_DEV_NAME_CREATION = 'LED_ET02_PEP_Lead_Creation_Template_for_Partners';
    public static final String S_PEP_LD_DEV_NAME_CONVERTED = 'LED_ET04_PEP_Lead_Conversion_Template_for_Partners';
    public static final String S_PEP_LD_DEV_NAME_REJECTED = 'LED_ET06_PEP_Lead_Rejection_Template_for_Partners';
    public static final String S_PEP_LED_RECORDTYPE = 'PRM_Lead';
    public static final String S_PEP_CTR_RECORDTYPE = 'PRM_Contract';
    public static final String S_PEP_CTR_DEV_NAME_RENEWALNOTIF ='CTR_ET01_PEP_Contract_Renewal_expiry_date';
    public static final String S_PEP_ACTIVE_STATUS ='Active';
    public static final String S_PEP_CONTRACT_FIRSTNOTIFICATION ='Contract Reminder_First';
    public static final String S_PEP_CONTRACT_SECONDNOTIFICATION ='Contract Reminder_Second';
    public static final String S_PEP_CONTRACT_THIRDNOTIFICATION ='Contract Reminder_Third';
    public static final String S_PEP_CONTRACT_EXPIREDNOTIFICATION ='Contract Reminder_Expired';
    public static final String S_PEP_LED_CLOSED_WON = 'Closed - Opportunity Won';
    public static final String S_PEP_LED_CLOSED_LOST = 'Closed - Opportunity Lost';
    public static final String S_PEP_OPP_CLOSED_WON = '7a. Closed Won';
    public static final String S_PEP_OPP_CLOSED_LOST = '7b. Closed Lost';
    public static final String S_PEP_POWERPARTNER = 'PowerPartner';
    public static final String S_PEP_LD_STATUS_NOT_STARTED = 'Not Started';
    public static final String S_ACTIVE = 'Active';
    public static final String S_INACTIVE = 'Inactive';
    public static boolean runFutureMethod = true;
    public static final String S_PEP_CLM_FOLDER = 'Samples';
    public static final String S_PEP_SOURCE = 'PRM';
}